---
kind: Deployment
apiVersion: v1
metadata:
  name: green
  labels:
    app: myapp
    version: "1.01"
spec:
  replicas: 1
  selector:
    app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: awony/capstone
        ports:
        - name: http-server
          containerPort: 80
