---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-1.01
  labels:
    name: myapp
    version: "1.01"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: awony/capstone
        ports:
        - name: http-server
          containerPort: 80
